name: Push updated values for application containers to the config repo

on:
  release:
    types: [published]
  push:
    branches: ['main']

jobs:
  push-updates-to-config:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Clone the config repo
        uses: actions/checkout@v3
        with:
          repository: jconnor0426/argocd-monitoring-mwdb
          path: config-repo
          ref: main
      
      - name: output config repo
        run: |
          ls -r config-repo
    
      # Figure out what the new values should be
      - name: Get submodule container image updates
        run: |
          for submodule_info in $(git submodule status --cached | grep submodules); do 
            
            SHORT_SHA=$(echo $submodule_info | cut -d " " -f 2)
            echo $SHORT_SHA
            SHORT_SHA=$(git rev-parse --short $SHORT_SHA)
            echo $SHORT_SHA
            IMAGE=$(echo $submodule_info | cut -d " " -f 3)

            echo ${IMAGE}:${SHORT_SHA}
            
          done
