name: Push updated values for application containers to the config repo

on:
  release:
    types: [published]
  push:
    branches: ['main']

jobs:
  push-updates-to-config:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Clone the config repo
        uses: actions/checkout@v3
        with:
          repository: jconnor0426/argocd-monitoring-mwdb
          path: config-repo
          ref: main
      
      - name: output config repo
        run: |
          ls -r config-repo
    
      # Figure out what the new values should be
      - name: Get submodule container image updates
        run: |
          git submodule status --cached | grep submodules > /tmp/submodules.txt
          cat /tmp/submodules.txt | while read line 
          do
            echo Debugging:"${line}"
            SHORT_SHA=$(echo $line | cut -d " " -f 1)
            SHORT_SHA=$(git rev-parse --short $SHORT_SHA)
            IMAGE=$(echo $line | cut -d " " -f 3 | cut -d "/" -f 2)
            echo $IMAGE $SHORT_SHA
          done
